apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "base-chart.fullname" . }}-msa-db
  labels:
    app: msa-db
  {{- include "base-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.msaDb.replicas }}
  selector:
    matchLabels:
      app: msa-db
  serviceName: {{ include "base-chart.fullname" . }}-headless
  template:
    metadata:
      labels:
        app: msa-db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ quote .Values.msaDb.mysql.env.mysqlRootPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.msaDb.mysql.image.repository }}:{{ .Values.msaDb.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - hostPath:
          path: /data/mysql
          type: DirectoryOrCreate
        name: mysql-storage
  updateStrategy: {}